Feature/ivr attachment filename
greatnonprofits-nfp/floweditor pull request #121
Opened 2024-07-08 13:33 UTC by ihor-palii

2024-07-08 14:45 UTC, teehamaral commented
@ihor-palii do you have a screenshot of this?

2024-07-08 16:59 UTC, ihor-palii commented
![Знімок екрана 2024-07-08 о 19 58 16](https://github.com/communityconnectlabs/floweditor/assets/57485784/657b57c2-28ce-4a52-98c9-6a54c56dfd87)
![Знімок екрана 2024-07-08 о 19 58 23](https://github.com/communityconnectlabs/floweditor/assets/57485784/6031f347-09a3-4cd5-a852-9a53cf54153c)

2024-07-09 15:34 UTC, teehamaral requested changes

2024-07-09 15:34 UTC, teehamaral commented on package.json
> +  "version": "1.17.8",
Would it not be version 1.17.7? https://www.npmjs.com/package/@greatnonprofits-nfp/flow-editor?activeTab=versions

2024-07-12 20:08 UTC, merged