Feature: Context menu
greatnonprofits-nfp/floweditor pull request #73
Opened 2020-11-03 21:12 UTC by ihor-palii

Feature: https://app.asana.com/0/1159876841343611/1178574019781755/f
Feature: https://app.asana.com/0/1159876841343611/1183030300553968/f

2020-11-04 21:58 UTC, teehamaral requested changes

2020-11-04 21:58 UTC, teehamaral commented on src/components/flow/Flow.tsx
> +        console.error(e);
Can we remove the console logs?

2020-11-04 21:58 UTC, teehamaral commented on src/components/contextmenu/ContextMenu.tsx
> +          style={{ left: this.state.left + 'px', top: this.state.top + 'px' }}
For string concatenation, can we use template strings https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals?

2020-11-05 12:13 UTC, ihor-palii commented on src/components/flow/Flow.tsx
> +        console.error(e);
I removed logs.

2020-11-05 12:14 UTC, teehamaral approved these changes

2020-11-05 20:51 UTC, merged